* VPA Workshop, SC'14

Today, I'm attending to the [[http://cedmav.org/vpa2014.html][1st VPA Workshop]], at [[http://conferences.computer.org/vpa/2014/][SC'14]]

*** Visualization of Performance Data for MPI Applications Using Circular Hierarchies

Unfortunately, I missed the first presentation.
The paper is available [[http://conferences.computer.org/vpa/2014/papers/7058a001.pdf][here]].
It seems to be an interesting way to represent communications between nodes using a circular hierarchy. Looks a bit like ExtraVis.

*** TorusVis?ND: Unraveling High-Dimensional Torus Networks for Network Traffic Visualizations

The paper is available [[http://conferences.computer.org/vpa/2014/papers/7058a009.pdf][here]]

- TorusVis
- Node representation and selection
- There is a time slice selection, same kind of principle than Triva
- Shneiderman approach filled -> data exploration, from top to more details
- Interaction: selection, filtering, brushing
- Future work: 
  - Scalability
  - Multiresolution capabilities
  - Multiperspective?

*** Down to Earth - How to Visualize Traffic on High-dimensional Torus Networks

[[Paper]]
